name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Composer
        uses: nanasess/composer-installer-action@v2.0.1

      - name: Debug
        run: |
          composer self-update --1
          composer --version
